- name: Standardize infrastructure
  hosts: all
  gather_facts: false

  vars_files:
    - config.yml

  # Les couches seront ajoutées ici dans leur ordre d'exécution (1 à 9)
  # à mesure qu'elles seront implémentées.
  roles:
    - role: 2_os_base_system
      tags: [os_base]

    - role: 3_identity_access
      tags: [identity_access]
