---
- name: Refresh APT package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ os_base_apt_cache_valid_time }}"

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: "{{ os_base_apt_upgrade_mode }}"
  when: os_base_upgrade_packages | bool

- name: Remove packages that are no longer required
  ansible.builtin.apt:
    autoremove: true
    purge: true
  when: os_base_autoremove_packages | bool

- name: Clean obsolete APT package files
  ansible.builtin.apt:
    autoclean: true
  when: os_base_autoclean_packages | bool
